library(dplyr)
library(lubridate)
powerdata<-read.table("household_power_consumption.txt",sep=";",nrows=2880,skip=66637,na.strings = "?")
n<-read.table("household_power_consumption.txt",sep=";",nrows=1)
colnames(powerdata)<-as.vector(unname(unlist(n[1,])))
powerdata<-mutate(powerdata,date_time = dmy_hms(paste(Date,Time)))
png(file="plot4.png")
par(mfrow=c(2,2))
plot(powerdata$date_time,powerdata$Global_active_power,type="l",xlab="",ylab="Global Active Power")
plot(powerdata$date_time,powerdata$Voltage,type="l",xlab="datetime",ylab="Voltage")
plot(powerdata$date_time,powerdata$Sub_metering_1,xlab = "",ylab="Energy sub metering",type = "l")
  lines(powerdata$date_time,powerdata$Sub_metering_2,col="red")
  lines(powerdata$date_time,powerdata$Sub_metering_3,col="blue")
  legend(x="topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lty=1,bty="n")
plot(powerdata$date_time,powerdata$Global_reactive_power,type="l",xlab="datetime",ylab="Global_reactive_power")
dev.off()