library(dplyr)
library(lubridate)
powerdata<-read.table("household_power_consumption.txt",sep=";",nrows=2880,skip=66637,na.strings = "?")
n<-read.table("household_power_consumption.txt",sep=";",nrows=1)
colnames(powerdata)<-as.vector(unname(unlist(n[1,])))
powerdata<-mutate(powerdata,date_time = dmy_hms(paste(Date,Time)))
png(file="plot2.png")
plot(powerdata$date_time,powerdata$Global_active_power,type="l",xlab="",ylab="Global Active Power (kilowatts)")
dev.off()
